### ISSUE TITLE
Errors during enrollment

### ISSUE THREAD

**Issue by jafeelv** [asajim/strong-software-based-Physical-Unclonable-Function#8]
When compiling MainEnrollment.py in Section 2, it shows that "Error opening challenge file on microSD". I don't know why there is an error!

**Comment by myndcryme** [comment]
The error is because nothing was ever written to the sdcard, so opening fails.  Make sure your card is formatted properly.  Read all these notes, make any appropriate changes and let me know if it resolves the error:

https://learn.adafruit.com/adafruit-micro-sd-breakout-board-card-tutorial/look-out

**Comment by jafeelv** [comment]
@myndcryme It is solved. The issue was with the microSD adapter. But I'm facing an issue with the reconstruction of the key.
